# Generated by Django 5.2.7 on 2025-12-11 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0004_alter_org_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=200)),
                ('rule_description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('RESOLVED', 'Resolved'), ('INVESTIGATING', 'Under Investigation'), ('IGNORED', 'False Positive')], default='PENDING', max_length=15)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('recommendation', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_audits', to='organization.org')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='ViolationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('CONSENT_VIOLATION', 'Consent Violation'), ('DATA_RETENTION', 'Data Retention Policy Violation'), ('ACCESS_CONTROL', 'Unauthorized Access'), ('PRIVACY_BREACH', 'Privacy Breach'), ('AUDIT_FAILURE', 'Audit Trail Failure'), ('PURPOSE_LIMITATION', 'Purpose Limitation Violation')], max_length=50)),
                ('description', models.TextField()),
                ('affected_users_count', models.IntegerField(default=0)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('reported_to_dpo', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation_reports', to='organization.org')),
                ('related_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compliance.complianceaudit')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='complianceaudit',
            index=models.Index(fields=['organization', '-detected_at'], name='compliance_organiz_0_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceaudit',
            index=models.Index(fields=['status', 'severity'], name='compliance_status_1_idx'),
        ),
        migrations.AddIndex(
            model_name='violationreport',
            index=models.Index(fields=['organization', '-detected_at'], name='compliance_organiz_2_idx'),
        ),
        migrations.AddIndex(
            model_name='violationreport',
            index=models.Index(fields=['violation_type', 'resolved'], name='compliance_violati_3_idx'),
        ),
    ]

