# Generated by Django 5.2.7 on 2025-11-09 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='address',
            field=models.CharField(default='', max_length=700),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='org',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_role': 'organization'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
