# Generated by Django 5.2.7 on 2025-12-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_org_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='trust_certificate_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='org',
            name='trust_certificate_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='trust_level',
            field=models.CharField(choices=[('EXCELLENT', 'Excellent'), ('VERIFIED', 'Verified'), ('GOOD', 'Good'), ('BASIC', 'Basic'), ('LOW', 'Low')], default='BASIC', max_length=20),
        ),
        migrations.AddField(
            model_name='org',
            name='trust_score',
            field=models.FloatField(default=0.0, help_text='Overall trust score (0-100)'),
        ),
        migrations.AddField(
            model_name='org',
            name='trust_score_last_calculated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='org',
            index=models.Index(fields=['-trust_score'], name='organization_trust_s_0_idx'),
        ),
        migrations.AddIndex(
            model_name='org',
            index=models.Index(fields=['trust_level'], name='organization_trust_l_1_idx'),
        ),
    ]

