# Generated by Django 5.2.7 on 2025-12-11 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_org_trust_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=100)),
                ('data_snapshot', models.JSONField()),
                ('checksum', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrity_records', to='organization.org')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='integrityrecord',
            index=models.Index(fields=['organization', '-created_at'], name='organization_organiz_2_idx'),
        ),
        migrations.AddIndex(
            model_name='integrityrecord',
            index=models.Index(fields=['entity_type', 'entity_id'], name='organization_entity__3_idx'),
        ),
    ]

