# Generated by Django 5.2.7 on 2025-11-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consent',
            name='user',
        ),
    ]
