# Generated by Django 5.2.7 on 2025-11-06 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0002_remove_consent_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.BooleanField(default=False)),
                ('consent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consents.consent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'consent')},
            },
        ),
    ]
