# Generated by Django 5.2.7 on 2025-11-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0003_userconsent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consent',
            name='access',
        ),
    ]
