# Generated by Django 5.2.7 on 2025-12-11 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0004_remove_consent_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userconsent',
            name='duration_days',
            field=models.IntegerField(blank=True, help_text='Consent duration in days (null = indefinite)', null=True),
        ),
        migrations.AddField(
            model_name='userconsent',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Optional expiry date for consent', null=True),
        ),
        migrations.AddField(
            model_name='userconsent',
            name='granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userconsent',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='userconsent',
            index=models.Index(fields=['user', '-granted_at'], name='consents_use_user_id_0_idx'),
        ),
        migrations.AddIndex(
            model_name='userconsent',
            index=models.Index(fields=['expires_at'], name='consents_use_expires_1_idx'),
        ),
        migrations.CreateModel(
            name='ConsentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('GRANTED', 'Granted'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired'), ('MODIFIED', 'Modified')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('previous_value', models.BooleanField(blank=True, null=True)),
                ('new_value', models.BooleanField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for the change')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user_consent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consents.userconsent')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='consenthistory',
            index=models.Index(fields=['user_consent', '-changed_at'], name='consents_con_user_co_2_idx'),
        ),
        migrations.AddIndex(
            model_name='consenthistory',
            index=models.Index(fields=['action', '-changed_at'], name='consents_con_action_3_idx'),
        ),
    ]

